export const GET_POKEMONSALL = 'GET_POKEMONSALL';
export const POST_POKEMONS = 'POST_POKEMONS';
export const GET_DETAIL = 'GET_DETAIL';
export const GET_POKEMON = 'GET_POKEMON';
export const GET_ASD_POKEMON = 'GET_ASD_POKEMON';
export const GET_DES_POKEMON = 'GET_DES_POKEMON';
