export const GET_POKEMONSALL = 'GET_POKEMONSALL';
export const GET_DETAIL = 'GET_DETAIL';
export const GET_TYPES = 'GET_TYPES';
export const GET_POKEMON = 'GET_POKEMON';
export const FILTERS_POKEMONS = 'FILTERS_POKEMONS';
